export const SET_POPUPPAGE_MASKER = "SET_POPUPPAGE_MASKER";
export const SET_POPUPPAGE_FIRST = "SET_POPUPPAGE_FIRST";
export const SET_POPUPPAGE_SECOND = "SET_POPUPPAGE_SECOND";
export const SET_POPUPPAGE_THIRD = "SET_POPUPPAGE_THIRD";
export const SET_POPUPPAGE_FOURTH = "SET_POPUPPAGE_FOURTH";
export const SET_POPUPPAGE_FIFTH = "SET_POPUPPAGE_FIFTH";
export const SET_PROPS_STATE = "SET_PROPS_STATE";

// login
export const SERVER_TIME = "SERVER_TIME";
export const LOGIN = "LOGIN";
export const VERIFYCODE = "VERIFYCODE";
export const REGISTER = "REGISTER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const EXPERIENCE = "EXPERIENCE";
export const GET_PERMISSION_INFO = "GET_PERMISSION_INFO";
export const GET_TRADE_SERVER_LIST = "GET_TRADE_SERVER_LIST";
export const GET_TRADE_RETAIL_LIST = "GET_TRADE_RETAIL_LIST";

// member
export const MEMBER_LIST = "MEMBER_LIST";
export const MEMBER_LIST2 = "MEMBER_LIST2";
export const MEMBER_FLESE = "MEMBER_FLESE";
export const MEMBER_YUCI = "MEMBER_YUCI";
export const MEMBER_TIME = "MEMBER_TIME";
export const MEMBER_TIME_EXPORT = "MEMBER_TIME_EXPORT";
export const MEMBER_ITEM = "MEMBER_ITEM";
export const MEMBER_ITEM2 = "MEMBER_ITEM2";
export const SET_REPORTLOSS = "SET_REPORTLOSS";
export const GET_MEMBER_LEVEL = "GET_MEMBER_LEVEL";
export const ADD_MEMEBER = "ADD_MEMEBER";
export const EDIT_MEMEBER = "EDIT_MEMEBER";
export const GET_MEMBER_EXPORTDATA = "GET_MEMBER_EXPORTDATA";
export const MEMBER_IMPORTDATA = "MEMBER_IMPORTDATA";
export const MEMBER_IMPORTDATA_CARD = "MEMBER_IMPORTDATA_CARD";
export const GET_MEMBER_SPENDING = "GET_MEMBER_SPENDING";
export const GET_MEMBER_BALANCE = "GET_MEMBER_BALANCE";
export const GET_MEMBER_INTEGRAL = "GET_MEMBER_INTEGRAL";
export const GET_MEMBER_ARREARS = "GET_MEMBER_ARREARS";
export const REPAY_MEMBER_ARREARS = "REPAY_MEMBER_ARREARS";
export const GET_MEMBER_FLAG = "GET_MEMBER_FLAG";
export const MEMBER_BALANCE_ADJUST = "MEMBER_BALANCE_ADJUST";
export const MEMBER_RECHARGE = "MEMBER_RECHARGE";
export const MEMBER_INTEGRAL_ADJUST = "MEMBER_INTEGRAL_ADJUST";
export const MEMBER_CARDS_ADJUST = "MEMBER_CARDS_ADJUST";
export const MEMBER_CARDS_ADJUST_TIME = "MEMBER_CARDS_ADJUST_TIME";
export const MEMBER_PROMOTION_LIST = "MEMBER_PROMOTION_LIST";
export const EITMEMBER_PROMOTION_LIST = "EITMEMBER_PROMOTION_LIST";
export const GET_MEMBER_COUNT = "GET_MEMBER_COUNT";
export const GET_MEMBER_SHOP = "GET_MEMBER_SHOP";
export const DEL_MEMBER = "DEL_MEMBER";
export const MEMBER_CODE = "MEMBER_CODE";
export const GET_AUTOVIPCODE = "GET_AUTOVIPCODE";
export const GET_MEMBER_BRITHDAY = "GET_MEMBER_BRITHDAY";
export const GET_MEMBER_FOLLOWUP = "GET_MEMBER_FOLLOWUP";
export const GET_MEMBER_FOLLOWUP_DEL = "GET_MEMBER_FOLLOWUP_DEL";
export const GET_MEMBER_FOLLOWUP_EIT = "GET_MEMBER_FOLLOWUP_EIT";
export const GET_MEMBER_PASSWD = "GET_MEMBER_PASSWD";
export const SAVE_VIP_IMG = "SAVE_VIP_IMG";
export const MODIFY_VIP_PASSWD = "MODIFY_VIP_PASSWD";
export const NEW_MEMBER_INTEGRAL_ADJUST = "NEW_MEMBER_INTEGRAL_ADJUST";
export const VIP_BIRTHDAY_REMINDER_LIST = "VIP_BIRTHDAY_REMINDER_LIST";
export const VIP_OVERDUE_REMINDER_LIST = "VIP_OVERDUE_REMINDER_LIST";
export const GET_NEWVIP_LIST = "GET_NEWVIP_LIST";
export const VIPCODE_ADD_DATE = "VIPCODE_ADD_DATE";
export const CONTEST_LIST = "CONTEST_LIST";
export const CONSUME_LIST = "CONSUME_LIST";
export const PARTICIPATE_LIST = "PARTICIPATE_LIST";

// shop
export const GET_SHOP_LIST = "GET_SHOP_LIST";
export const GET_SHOP_ITEM = " GET_SHOP_ITEM";
export const SHOP_STATE = "SHOP_STATE";
export const DEL_SHOP_STATE = "DEL_SHOP_STATE";
// employee
export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const GET_EMPLOYEE_SORT_DATA = "GET_EMPLOYEE_SORT_DATA";
export const GET_EMPLOYEE_SORT_LIST = "GET_EMPLOYEE_SORT_LIST";
export const GET_EMPLOYEE_SORT_ITEM = "GET_EMPLOYEE_SORT_ITEM";
export const GET_EMPLOYEE_ACHIEVEMENT = "GET_EMPLOYEE_ACHIEVEMENT";
export const GET_EMPLOYEE_BESPEAK = "GET_EMPLOYEE_BESPEAK";
export const GET_EMPLOYEE_ITEM = "GET_EMPLOYEE_ITEM";
export const GET_DELEMPLOYEE_STATE = "GET_DELEMPLOYEE_STATE";
export const GET_EMPLOYEE_POST = "GET_EMPLOYEE_POST";
export const GET_JOB_LIST = "GET_JOB_LIST";
// level
export const GET_LEVEL_LIST = "GET_LEVEL_LIST";
export const GET_LEVEL_ITEM = "GET_LEVEL_ITEM";
export const DEAL_LEVEL_ITEM = "DEAL_LEVEL_ITEM";
// UNIT
export const GET_UNIT_LIST = "GET_UNIT_LIST";
export const GET_UNIT_ITEM = "GET_UNIT_ITEM";
export const DEAL_UNIT_ITEM = "DEAL_UNIT_ITEM";
//CATEGORY
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_CATEGORY_ITEM = "GET_CATEGORY_ITEM";
export const DEAL_CATEGORY_ITEM = "DEAL_CATEGORY_ITEM";
// payment
export const GET_PAYMENT_LIST = "GET_PAYMENT_LIST";
export const GET_PAYWAY_LIST = "GET_PAYWAY_LIST";
export const DEAL_PAYMENT = "DEAL_PAYMENT";
export const ADD_PAYWAY = "ADD_PAYWAY";
export const DEL_PAYWAY = "DEL_PAYWAY";
export const SORT_PAYWAY = "SORT_PAYWAY";
// address
export const ADDRESS_STATE = "ADDRESS_STATE";

// goods
export const GOODS_LIST = "GOODS_LIST";
export const GOODS_LIST_NEW = "GOODS_LIST_NEW";
export const GOODS_LIST2 = "GOODS_LIST2";
export const GOODS_LIST3 = "GOODS_LIST3";
export const GOODS_LIST4 = "GOODS_LIST4";
export const GOODS_ITEM = "GOODS_ITEM";
export const GOODS_ITEM2 = "GOODS_ITEM2";
export const DEAL_GOODS = "DEAL_GOODS";
export const GOODS_EXPORTDATA = "GOODS_EXPORTDATA";
export const GOODS_IMPORTDATA = "GOODS_IMPORTDATA";
export const SET_GOODS_MOVING = "SET_GOODS_MOVING";
export const GET_GOODS_INVENTORY = "GET_GOODS_INVENTORY";
export const GET_GOODS_SETMEALG = "GET_GOODS_SETMEALG";
export const GET_GOODS_SETMEALGSAVE = "GET_GOODS_SETMEALGSAVE";
export const GET_GOODS_SETMEALGDETAILS = "GET_GOODS_SETMEALGDETAILS";
export const UPLOAD_STATE = "UPLOAD_STATE";
export const DEAL_IMAGE = "DEAL_IMAGE";
export const GET_IMAGES_LIST = "GET_IMAGES_LIST";
export const UPLOAD_CRO_STATE = "UPLOAD_CRO_STATE";
export const GET_GOODS_DELETE = "GET_GOODS_DELETE";
export const PUT_RETRIEVAL_DATA = "PUT_RETRIEVAL_DATA";
export const GOODS_CODE = "GOODS_CODE";
export const GET_WAREHOUSING_BILLID = "GET_WAREHOUSING_BILLID";

export const UPLOAD_STOCK_STATE = "UPLOAD_STOCK_STATE";
export const BILLID_DETAILS_CHECK = "BILLID_DETAILS_CHECK";

// |-- stock ==> warehousing  采购入库
export const WAREHOUSING_LIST = "WAREHOUSING_LIST";
export const WAREHOUSING_ADD = "WAREHOUSING_ADD";
export const WAREHOUSING_ITEM = "WAREHOUSING_ITEM";
export const WAREHOUSING_CANCEL = "WAREHOUSING_CANCEL";
export const WAREHOUSING_EXPORT_TABLE = "WAREHOUSING_EXPORT_TABLE";
export const CGD_WAREHOUSING_DATA = "CGD_WAREHOUSING_DATA";

// |-- stock ==> return  采购退货
export const RETURN_LIST = "RETURN_LIST";
export const RETURN_ADD = "RETURN_ADD";
export const RETURN_ITEM = "RETURN_ITEM";
export const RETURN_CANCEL = "RETURN_CANCEL";
export const RETURN_EXPORT_TABLE = "RETURN_EXPORT_TABLE";
export const CGD_RETURN_DATA = "CGD_RETURN_DATA";

// !-- stock ==> allocation   库存调拨
export const ALLOCATION_LIST = "ALLOCATION_LIST";
export const ALLOCATION_ADD = "ALLOCATION_ADD";
export const ALLOCATION_ITEM = "ALLOCATION_ITEM";
export const ALLOCATION_CANCEL = "ALLOCATION_CANCEL";
export const ALLOCATION_EXPORT_TABLE = "ALLOCATION_EXPORT_TABLE";
export const SAVE_ALLOCATION_BILL = "SAVE_ALLOCATION_BILL";
export const CGD_ALLOCATION_DATA = "CGD_ALLOCATION_DATA";

// !-- stock ==> inventory   库存盘点
export const INVENTORY_LIST = "INVENTORY_LIST";
export const INVENTORY_ADD = "INVENTORY_ADD";
export const INVENTORY_ITEM = "INVENTORY_ITEM";
export const INVENTORY_CANCEL = "INVENTORY_CANCEL";
export const INVENTORY_EXPORT_TABLE = "INVENTORY_EXPORT_TABLE";
export const CGD_INVENTORY_DATA = "CGD_INVENTORY_DATA";

export const GET_WAREHOUSING_REPORT = "GET_WAREHOUSING_REPORT";
export const EXPORT_WAREHOUSING_REPORT = "EXPORT_WAREHOUSING_REPORT";
export const GET_SALE_CENSUS_REPORT = "GET_SALE_CENSUS_REPORT";
export const GET_Allocation_REPORT = "GET_Allocation_REPORT";
export const GET_Inventory_REPORT = "GET_Inventory_REPORT";
export const GET_STOCK_QI_LIST = "GET_STOCK_QI_LIST";
export const GET_STOCK_DETAILS = "GET_STOCK_DETAILS";
export const GET_STOCK_TOTAl = "GET_STOCK_TOTAl";

// service
export const SERVICE_REVISIT_LIST = "SERVICE_REVISIT_LIST";
export const SERVICE_REVISIT_ITEM = "SERVICE_REVISIT_ITEM";
export const SERVICE_INTENTION_LIST = "SERVICE_INTENTION_LIST";
export const SERVICE_INTENTION_ITEM = "SERVICE_INTENTION_ITEM";
export const SERVICE_INTENTION_STATE = "SERVICE_INTENTION_STATE";
export const SERVICE_INTENTION_DEAL = "SERVICE_INTENTION_DEAL";
export const SERVICE_INTENTION_CHANGE = "SERVICE_INTENTION_CHANGE";
export const SERVICE_OPINION_LIST = "SERVICE_OPINION_LIST";
export const SERVICE_OPINION_ITEM = "SERVICE_OPINION_ITEM";
export const SERVICE_OPINION_STATE = "SERVICE_OPINION_STATE";
export const SERVICE_NOURISHING_LIST = "SERVICE_NOURISHING_LIST";
export const SERVICE_NOURISHING_ITEM = "SERVICE_NOURISHING_ITEM";

// Marketing
export const MARKETING_LIST = "MARKETING_LIST";
export const MARKETING_SHOP_LIST = "MARKETING_SHOP_LIST";
export const MARKETING_SHOP_LIST2 = "MARKETING_SHOP_LIST2";
export const MARKETING_SHOP_LISTS = "MARKETING_SHOP_LISTS";
export const MARKETING_LOT_LIST = "MARKETING_LOT_LIST";
export const MARKETING_ITEM = "MARKETING_ITEM";
export const STOP_MARKETING_ACTION = "STOP_MARKETING_ACTION";
export const DEAL_MARKETING_ACTION = "DEAL_MARKETING_ACTION";
export const MARKETING_LIST_IMG = "MARKETING_LIST_IMG";
export const MARKETING_RECHARGE_LIST = "MARKETING_RECHARGE_LIST";
export const MARKETING_RECHARGE_ADD = "MARKETING_RECHARGE_ADD";
export const MARKETING_SAVE_IMG = "MARKETING_SAVE_IMG";
export const MARKETING_DEL_IMG = "MARKETING_DEL_IMG";
export const MARKETING_RECHARGE_DETAILED = "MARKETING_RECHARGE_DETAILED";
export const MARKETING_RECHARGE_EIT = "MARKETING_RECHARGE_EIT";
export const MARKETING_RECHARGE_STATYS = "MARKETING_RECHARGE_STATYS";
export const MARKETING_RECHARGE_SMSSIGN = "MARKETING_RECHARGE_SMSSIGN";

export const GET_REGISTERGIFTS_DATA = "GET_REGISTERGIFTS_DATA";
export const GET_REGISTERGIFTS_ITEM = "GET_REGISTERGIFTS_ITEM";
export const DEAL_REGISTERGIFTS = "DEAL_REGISTERGIFTS";
export const DEL_REGISTERGIFTS = "DEL_REGISTERGIFTS";
export const GET_REGISTERGIFTS_DEL = "GET_REGISTERGIFTS_DEL";

export const SAVE_SPECIALS = "SAVE_SPECIALS";
export const GET_SPECIALS_LIST = "GET_SPECIALS_LIST";
export const SPECIALS_ITEM = "SPECIALS_ITEM";
export const DEL_SPECIALS = "DEL_SPECIALS";

export const SAVE_RecommendGifts = "SAVE_RecommendGifts";
export const GET_RecommendGifts_ITEM = "GET_RecommendGifts_ITEM";
export const GET_RECOMMEND_LIST = "GET_RECOMMEND_LIST";
export const GET_INCOME_ITEM = "GET_INCOME_ITEM";
export const GET_INCOME_INFO = "GET_INCOME_INFO";
export const GET_BespeakDate_LIST = "GET_BespeakDate_LIST";
export const GET_BespeakTime_LIST = "GET_BespeakTime_LIST";

export const GET_APPLICATION_LIST = "GET_APPLICATION_LIST";
export const SET_APPLICATION_STATE = "SET_APPLICATION_STATE";
export const SET_VIPCARD_BACKGROUND = "SET_VIPCARD_BACKGROUND";
export const GET_VIPCARD_BACKGROUND = "GET_VIPCARD_BACKGROUND";

export const GET_INTEGRAL_RESET_LIST = "GET_INTEGRAL_RESET_LIST";
export const DEL_INTEGRAL_RESET = "DEL_INTEGRAL_RESET";
export const SAVE_INTEGRAL_RESET = "SAVE_INTEGRAL_RESET";
export const DETAIL_INTEGRAL_RESET = "DETAIL_INTEGRAL_RESET";

export const GETGAMEGOODS_COUPON_LIST = 'GETGAMEGOODS_COUPON_LIST'
export const ADD_GAMEGOODS_COUPON = 'ADD_GAMEGOODS_COUPON'
export const OPEN_CLOSE_COUPON = 'OPEN_CLOSE_COUPON'
export const COUPON_GET_DETAILS = 'COUPON_GET_DETAILS'
export const DEL_GETCOUPON = 'DEL_GETCOUPON'
export const CANCEL_ALL_COUPON = 'CANCEL_ALL_COUPON'

// 预约
export const BESPEAK_LIST = "BESPEAK_LIST";
export const BESPEAK_LIST2 = "BESPEAK_LIST2";
export const EDIT_BESPEAK_STATUS = "EDIT_BESPEAK_STATUS";
export const DEAL_BESPEAK = "DEAL_BESPEAK";
export const WECHAT_LIST = "WECHAT_LIST";
export const SHIFTS_LIST = "SHIFTS_LIST";
export const SHIFTS_DEAL = "SHIFTS_DEAL";
export const SHIFTS_ITEM = "SHIFTS_ITEM";
export const SET_APPOINTMENTS = "SET_APPOINTMENTS";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_EMPLOY_PAIBAN = "GET_EMPLOY_PAIBAN";
export const SET_EMPLOYPAIBAN = "SET_EMPLOYPAIBAN";
export const GET_XIANGMU_LIST = "GET_XIANGMU_LIST";

// defray
export const DEFRAY_LIST = "DEFRAY_LIST";
export const DEAL_DEFRAY = "DEAL_DEFRAY";

// account
export const GET_ACCOUNT_LIST = "GET_ACCOUNT_LIST";
export const FIRST_ACCOUNT_MONEY = "FIRST_ACCOUNT_MONEY";
export const INOUT_ACCOUNT_PAY = "INOUT_ACCOUNT_PAY";
export const ACCOUNT_FLOW_LIST = "ACCOUNT_FLOW_LIST";
export const ADDACCOUNT = "ADDACCOUNT";

// report
export const GET_REPORT_LIST = "GET_REPORT_LIST";
export const GET_BUSINESS_DATA = "GET_BUSINESS_DATA";
export const GET_BUSINESS_LIST = "GET_BUSINESS_LIST";
export const CANCEL_BUSINESS_BILLS = "CANCEL_BUSINESS_BILLS";
export const GET_SURPLUS_DATA = "GET_SURPLUS_DATA";
export const GET_SURPLUS_LIST = "GET_SURPLUS_LIST";
export const GET_CHACKOUT_DATA = "GET_CHACKOUT_DATA";
export const GET_CHACKOUT_LIST = "GET_CHACKOUT_LIST";
export const GET_CHACKOUT_PAY_DATA = "GET_CHACKOUT_PAY_DATA";
export const GET_SALEREPORT_DATA = "GET_SALEREPORT_DATA";
export const GET_SALEREPORT_LIST = "GET_SALEREPORT_LIST";
export const GET_SALEINQUIRY_DATA = "GET_SALEINQUIRY_DATA";
export const GET_SALEINQUIRY_LIST = "GET_SALEINQUIRY_LIST";
export const GET_SALEINQUIRY_ITEM = "GET_SALEINQUIRY_ITEM";
export const GET_GOODSREPORT_DATA = "GET_GOODSREPORT_DATA";
export const GET_GOODSREPORT_LIST = "GET_GOODSREPORT_LIST";
export const GET_MEMBERREPORT_DATA = "GET_MEMBERREPORT_DATA";
export const GET_MEMBERREPORT_LIST = "GET_MEMBERREPORT_LIST";
export const GET_DEFRAYREPORT_DATA = "GET_DEFRAYREPORT_DATA";
export const GET_DEFRAYREPORT_LIST = "GET_DEFRAYREPORT_LIST";
export const GET_ACHIEVEMENT_DATA = "GET_ACHIEVEMENT_DATA";
export const GET_ACHIEVEMENT_EXPORTDATA = "GET_ACHIEVEMENT_EXPORTDATA";
export const GET_ACHIEVEMENT_LIST = "GET_ACHIEVEMENT_LIST";
export const GET_ACHIEVEMENT_ITEM = "GET_ACHIEVEMENT_ITEM";
export const GET_ORDERREPORT_DATA = "GET_ORDERREPORT_DATA";
export const GET_ORDERREPORT_LIST = "GET_ORDERREPORT_LIST";
export const GET_ORDERREPORT_ITEM = "GET_ORDERREPORT_ITEM";
export const GET_REGREPORT_DATA = "GET_REGREPORT_DATA";
export const GET_REGREPORT_DATAEXPORT = "GET_REGREPORT_DATAEXPORT";
export const GET_REGREPORT_LIST = "GET_REGREPORT_LIST";
export const GET_REGREPORT_ITEM = "GET_REGREPORT_ITEM";
export const GET_BALANCEREPORT_DATA = "GET_BALANCEREPORT_DATA";
export const GET_BALANCEREPORT_LIST = "GET_BALANCEREPORT_LIST";
export const GET_INTEGRAL_ADJUST_LIST = "GET_INTEGRAL_ADJUST_LIST";
export const GET_BALANCE_ADJUST_LIST = "GET_BALANCE_ADJUST_LIST";
export const GET_INTEGRAL_BALANCE_LIST = "GET_INTEGRAL_BALANCE_LIST";
export const GET_NUMBER_BALANCE_LIST = "GET_NUMBER_BALANCE_LIST";
export const GET_SALES_DETAILS = "GET_SALES_DETAILS";
export const SALEREPORT_EXPORT_TABLE = "SALEREPORT_EXPORT_TABLE";
export const GOODSREPORT_EXPORT_TABLE = "GOODSREPORT_EXPORT_TABLE";
export const MEMBERREPORT_EXPORT_TABLE = "MEMBERREPORT_EXPORT_TABLE";
export const DEFRAYREPORT_EXPORT_TABLE = "DEFRAYREPORT_EXPORT_TABLE";
export const BALANCEADJUST_EXPORT_TABLE = "BALANCEADJUST_EXPORT_TABLE";
export const INTEGRALADJUST_EXPORT_TABLE = "INTEGRALADJUST_EXPORT_TABLE";
export const NUMBERBALANCE_EXPORT_TABLE = "NUMBERBALANCE_EXPORT_TABLE";
export const ORDERREPORT_EXPORT_TABLE = "ORDERREPORT_EXPORT_TABLE";
export const MEMBER_EXPORT_TABLE = "MEMBER_EXPORT_TABLE";
export const SALEINQUIRY_EXPORT_TABLE = "SALEINQUIRY_EXPORT_TABLE";
export const SALEMONEY_EXPORT_TABLE = "SALEMONEY_EXPORT_TABLE";
export const MEMBER_TABLE_CHOZHI = "MEMBER_TABLE_CHOZHI";
export const MEMBER_TABLE_CHOZHIEXPORT = "MEMBER_TABLE_CHOZHIEXPORT";
export const CONSUME_STATISTICS_TABLE = "CONSUME_STATISTICS_TABLE";
export const INTEGRAL_STATISTICS_TABLE = "INTEGRAL_STATISTICS_TABLE";
export const INTEGRAL_DH_STATISTICS_TABLE = "INTEGRAL_DH_STATISTICS_TABLE";
export const ADJUST_TABLE = "ADJUST_TABLE";
export const STAFF_LIST_REPORT = "STAFF_LIST_REPORT";
export const REPORT_SHOP_LIST = "REPORT_SHOP_LIST";
export const TABLE_INVEST_CANCEL = "TABLE_INVEST_CANCEL";
export const MEMBER_TABLE_YUEREXPORT = "MEMBER_TABLE_YUEREXPORT";

//crossStore
export const GET_CROSSSTORE_DATA = "GET_CROSSSTORE_DATA";
export const GET_CROSSSTORE_SALES_ITEM = "GET_CROSSSTORE_SALES_ITEM";
export const GET_CROSSSTORE_RECHARGE_ITEM = "GET_CROSSSTORE_RECHARGE_ITEM";

// setup
export const MY_INFO = "MY_INFO";
export const GET_MY_SHOP = "GET_MY_SHOP";
export const EDIT_MY_INFO = "EDIT_MY_INFO";
export const GET_INDUSTRY = "GET_INDUSTRY";
export const REBUILD_DATA_FUN = "REBUILD_DATA_FUN";
export const SALE_PATTERN_STATE = "SALE_PATTERN_STATE";
export const GET_PERMISSION_LIST = "GET_PERMISSION_LIST";
export const SET_PERMISSION = "SET_PERMISSION";
export const GET_PARAMETERSTATE = "GET_PARAMETERSTATE";
export const SET_PARAMETERSTATE = "SET_PARAMETERSTATE";
export const GET_SHOP_VIPQTY = 'GET_SHOP_VIPQTY'

// |-- user
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_ITEM = "GET_USER_ITEM";
export const DEAL_USER_ITEM = "DEAL_USER_ITEM";
export const DEL_USER = "DEL_USER";
export const RESET_USER_PASSWORD = "RESET_USER_PASSWORD";
export const SET_PERMISSION_STORE = "SET_PERMISSION_STORE";
// |-- integral
export const GET_INTEGRAL_LIST = "GET_INTEGRAL_LIST";
export const GET_INTEGRAL_ITEM = "GET_INTEGRAL_ITEM";
export const DEAL_INTEGRAL_ITEM = "DEAL_INTEGRAL_ITEM";
export const INTEGRAL_STATE = "INTEGRAL_STATE";
// |-- royalty
export const SET_SELLING_CARDS = "SET_SELLING_CARDS";
export const SELLING_CARDS_LIST = "SELLING_CARDS_LIST";
export const SET_RECHARGE = "SET_RECHARGE";
export const GET_RECHARGE_VALUE = "GET_RECHARGE_VALUE";
export const SET_FASTCONSUME = "SET_FASTCONSUME";
export const SET_FASTCONSUME_VALUE = "SET_FASTCONSUME_VALUE";
export const SET_GOODSCONSUME = "SET_GOODSCONSUME";
export const SET_RECONCILIA_RATE = "SET_RECONCILIA_RATE";

//home
export const GET_HOME_WEEKSDAYTIME = "GET_HOME_WEEKSDAYTIME";
export const GET_NOTICE_INFO = "GET_NOTICE_INFO";
export const GET_SaleTable_DATA = "GET_SaleTable_DATA";
export const GET_PaiHang_Group = "GET_PaiHang_Group";
// ssmember
export const GET_SSMEMBERD_LIST = "GET_SSMEMBERD_LIST";
export const GET_SSMEMBERD_LIST1 = "GET_SSMEMBERD_LIST1";
//recharge
export const GET_RECHARGE_LIST = "GET_RECHARGE_LIST";
export const GET_INTEGRALT_LIST = "GET_INTEGRALT_LIST";
export const SAVE_VIP_RECHARGE = "SAVE_VIP_RECHARGE";
export const GET_BARCODEPAYF_LIST = "GET_BARCODEPAYF_LIST";
export const GET_BARCODEPAYT_LIST = "GET_BARCODEPAYT_LIST";
export const GET_BARCODEPAYOPEN_LIST = "GET_BARCODEPAYOPEN_LIST";
export const GET_COUPONLIST_LIST = "GET_COUPONLIST_LIST";
export const GET_COUPONCHECK_LIST = "GET_COUPONCHECK_LIST";
//checkout
export const GET_COMMODITYCFL_LIST = "GET_COMMODITYCFL_LIST";
export const GET_COMMODITYCCONSUMPTION = "GET_COMMODITYCCONSUMPTION";
export const GET_TIMESCOUNTCCONSUMPTION = "GET_TIMESCOUNTCCONSUMPTION";
export const GET_FASTCCONSUMPTION = "GET_FASTCCONSUMPTION";
export const GET_FASTCCROYALTY = "GET_FASTCCROYALTY";
export const GET_SRORAGEVALUERRECHARGE = "GET_SRORAGEVALUERRECHARGE";
export const GET_SRORAGEVALUERROYALTY = "GET_SRORAGEVALUERROYALTY";
export const GET_SETMEALRSELECT_LIST = "GET_SETMEALRSELECT_LIST";
export const GET_SETMEALRSELECT_DETAIL = "GET_SETMEALRSELECT_DETAIL";
export const GET_SETMEALRTIMERECHARGE = "GET_SETMEALRTIMERECHARGE";
export const GET_GUADANCX_LIST = "GET_GUADANCX_LIST";
export const GET_GUADANCD_LIST = "GET_GUADANCD_LIST";
export const GET_GUADANCDL_LIST = "GET_GUADANCDL_LIST";
export const DEL_GUADANCDL_LIST = "DEL_GUADANCDL_LIST";
export const GET_MEMBERQRCODEURL = "GET_MEMBERQRCODEURL";
export const GET_INTEGRAL_EXCHANGE = "GET_INTEGRAL_EXCHANGE";
export const GET_PERIOD = "GET_PERIOD";
export const FAST_PAYMONEY = "FAST_PAYMONEY";

//生意通折扣
export const GET_COMMODITYCFL_DISCOUNT = "GET_COMMODITYCFL_DISCOUNT";

export const GET_BUSINESS_TABLE = "GET_BUSINESS_TABLE";
export const EXPORT_BUSINESS_DERIVE = "EXPORT_BUSINESS_DERIVE";
export const GET_BUSINESS_TABLE_DETAILED = "GET_BUSINESS_TABLE_DETAILED";

// 消费结账
export const GET_CCGOODS_ITEM = "GET_CCGOODS_ITEM";
export const GET_CCNUMBER_ITEM = "GET_CCNUMBER_ITEM";

// room
export const ROOM_LIST = "ROOM_LIST";
export const ROOM_LIST2 = "ROOM_LIST2";
export const ROOM_ITEM = "ROOM_ITEM";
export const DEAL_ROOM_ITEM = "DEAL_ROOM_ITEM";
export const DEAL_ROOMORDER = "DEAL_ROOMORDER";
export const GET_ROOMORDER_LIST = "GET_ROOMORDER_LIST";
export const GET_ROOMORDER_ITEM = "GET_ROOMORDER_ITEM";
export const ROOMORDER_STATE = "ROOMORDER_STATE";
export const GET_ROOMORDER_TIME = "GET_ROOMORDER_TIME";
export const ROOM_AREA_LIST = "ROOM_AREA_LIST";
export const DEAL_ROOM_AREA = "DEAL_ROOM_AREA";
export const PRINT_ROOMORDER = "PRINT_ROOMORDER";
export const CANECL_ROOMORDER = "CANECL_ROOMORDER";

//supplier
export const SUPPLIER_LIST = "SUPPLIER_LIST";
export const SUPPLIER_ITEM = "SUPPLIER_ITEM";
export const SUPPLIER_SAVE = "SUPPLIER_SAVE";
export const SUPPLIER_CANCEL = "SUPPLIER_CANCEL";
export const SUPPLIERREPORT_LIST = "SUPPLIERREPORT_LIST";
export const SUPPLIER_REPORT_ITEM = "SUPPLIER_REPORT_ITEM";
export const SET_Supplier_FirstMoney = "SET_Supplier_FirstMoney";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const GET_GOODS_SUPPLIER = "GET_GOODS_SUPPLIER";
export const PAY_SUPPLIER = "PAY_SUPPLIER";

// maill
export const SETUP_MALL = "SETUP_MALL";
export const GET_SETUP_MALL = "GET_SETUP_MALL";
export const MALL_GOODS_LIST = "MALL_GOODS_LIST";
export const MALL_GOODS_ITEM = "MALL_GOODS_ITEM";
export const CHANGE_MALLGOODS_STATE = "CHANGE_MALLGOODS_STATE";
export const DEAL_MALL_GOODS = "DEAL_MALL_GOODS";
export const MALL_ORDER_LIST = "MALL_ORDER_LIST";
export const MALL_ORDER_ITEM = "MALL_ORDER_ITEM";
export const MALL_ORDER_STATE = "MALL_ORDER_STATE";
export const MALL_FREIGHT_LIST = "MALL_FREIGHT_LIST";
export const MALL_FREIGHT_ITEM = "MALL_FREIGHT_ITEM";
export const MALL_FREIGHT_DEAL = "MALL_FREIGHT_DEAL";
export const MALL_REDUCE_STOCK_TYPE = "MALL_REDUCE_STOCK_TYPE";
export const MALL_REFUND_LIST = "MALL_REFUND_LIST";
export const MALL_REFUND_ITEM = "MALL_REFUND_ITEM";
export const MALL_REFUND_STATE = "MALL_REFUND_STATE";
export const MALL_EXPRESS_LIST = "MALL_EXPRESS_LIST";
export const MALL_EXPRESS_DEAL = "MALL_EXPRESS_DEAL";
export const MALL_HOME = "MALL_HOME";
export const MALL_CLASS_LIST = "MALL_CLASS_LIST";
export const MALL_QRCODE = "MALL_QRCODE";

// game
export const GET_EVENTS_LIST = "GET_EVENTS_LIST";
export const GET_EVENTS_LIST_ALL = "GET_EVENTS_LIST_ALL";
export const GET_EVENTS_DETAILS = "GET_EVENTS_DETAILS";
export const SAVE_EVENTS = "SAVE_EVENTS";
export const DEL_EVENTS = "DEL_EVENTS";
export const SAVE_REWARDWAY = "SAVE_REWARDWAY";

export const GET_GAME_LIST = "GET_GAME_LIST";
export const GET_GAME_DETAILS = "GET_GAME_DETAILS";

export const GET_TABLE_LIST = "GET_TABLE_LIST";
export const SAVE_TABLE = "SAVE_TABLE";
export const DEL_TABLE = "DEL_TABLE";

// match - sng
export const SAVE_SNG_GAME = "SAVE_SNG_GAME";
export const SNG_CANCEL_GAME = "SNG_CANCEL_GAME";
export const SNG_EXIT_GAME = "SNG_EXIT_GAME";
export const EDIT_SNG_GAME = "EDIT_SNG_GAME";
export const SNG_START_SIGNUP = "SNG_START_SIGNUP";
export const SNG_CANCEL_VIP_REWARD = "SNG_CANCEL_VIP_REWARD";
export const SNG_CANCEL_REWARD = "SNG_CANCEL_REWARD";
export const SNG_SUBMIT_REWARD = "SNG_SUBMIT_REWARD";
export const SIGNUP_SCAN_VERIFITION = "SIGNUP_SCAN_VERIFITION";
export const SIGNUP_SCAN_LIST = "SIGNUP_SCAN_LIST";

// match - mtt
export const SAVE_MTT_GAME = "SAVE_MTT_GAME";
export const MTT_CANCEL_GAME = "MTT_CANCEL_GAME";
export const MTT_EXIT_GAME = "MTT_EXIT_GAME";
export const EDIT_MTT_GAME = "EDIT_MTT_GAME";
export const MTT_START_SIGNUP = "MTT_START_SIGNUP";
export const MTT_CANCEL_VIP_REWARD = "MTT_CANCEL_VIP_REWARD";
export const MTT_CANCEL_REWARD = "MTT_CANCEL_REWARD";
export const MTT_SUBMIT_REWARD = "MTT_SUBMIT_REWARD";

// match - integral
export const SAVE_INTEGRAL_GAME = "SAVE_INTEGRAL_GAME";
export const INTEGRAL_CANCEL_GAME = "INTEGRAL_CANCEL_GAME";
export const INTEGRAL_EXIT_GAME = "INTEGRAL_EXIT_GAME";
export const EDIT_INTEGRAL_GAME = "EDIT_INTEGRAL_GAME";
export const INTEGRAL_START_SIGNUP = "INTEGRAL_START_SIGNUP";
export const INTEGRAL_CANCEL_VIP_REWARD = "INTEGRAL_CANCEL_VIP_REWARD";
export const INTEGRAL_SUBMIT_REWARD = "INTEGRAL_SUBMIT_REWARD";
export const INTEGRAL_BUYOBJ = "INTEGRAL_BUYOBJ";
export const NO_PRIZE_LIST = "NO_PRIZE_LIST";

// [ modules 2 ]------------------------------------------------------------------------------
export const ACTIONS_STATE = "ACTIONS_STATE";
export const GET_LIST = "GET_LIST";
export const EXPORT_COMMON = "EXPORT_COMMON";

export const ACTIONS_STATE_management = "ACTIONS_STATE_management";
export const GET_LIST_managementA = "GET_LIST_managementA";
export const GET_LIST_managementB = "GET_LIST_managementB";
export const GET_LIST_managementC = "GET_LIST_managementC";
export const GET_LIST_managementD = "GET_LIST_managementD";
export const GET_LIST_managementE = "GET_LIST_managementE";
export const GET_LIST_managementF = "GET_LIST_managementF";
export const ACTIONS_STATE_balance = "ACTIONS_STATE_balance";
export const GET_LIST_balanceA = "GET_LIST_balanceA";
export const GET_LIST_balanceB = "GET_LIST_balanceB";
export const GET_LIST_balanceC = "GET_LIST_balanceC";
export const GET_LIST_balanceD = "GET_LIST_balanceD";
export const GET_LIST_balanceE = "GET_LIST_balanceE";
export const GET_LIST_balanceF = "GET_LIST_balanceF";
export const GET_LIST_balanceG = "GET_LIST_balanceG";
export const ACTIONS_STATE_cashier = "ACTIONS_STATE_cashier";
export const GET_LIST_match = "GET_LIST_match";
export const ACTIONS_STATE_matchItem = "ACTIONS_STATE_matchItem";
export const GET_LIST_matchProList = "GET_LIST_matchProList";
export const GET_LIST_matchCheckIn = "GET_LIST_matchCheckIn";
export const ACTIONS_STATE_hour = "ACTIONS_STATE_hour";
export const ACTIONS_STATE_week = "ACTIONS_STATE_week";
export const GET_LIST_fast = "GET_LIST_fast";
export const ACTIONS_STATE_sale = "ACTIONS_STATE_sale";
export const GET_LIST_saleItem = "GET_LIST_saleItem";
export const GET_LIST_goods = "GET_LIST_goods";
export const GET_LIST_goodsItem = "GET_LIST_goodsItem";
export const GET_LIST_shop = "GET_LIST_shop";
export const ACTIONS_STATE_member = "ACTIONS_STATE_member";
export const ACTIONS_STATE_memberRegChart = "ACTIONS_STATE_memberRegChart";
export const GET_LIST_memberRegister = "GET_LIST_memberRegister";
export const GET_LIST_memberRegisterItem = "GET_LIST_memberRegisterItem";
export const GET_LIST_memberRecharge = "GET_LIST_memberRecharge";
export const GET_LIST_memberAward = "GET_LIST_memberAward";
export const GET_LIST_goodsSale = "GET_LIST_goodsSale";
export const GET_LIST_goodsSaleA = "GET_LIST_goodsSaleA";
export const GET_LIST_goodsSaleB = "GET_LIST_goodsSaleB";
export const GET_LIST_goodsSaleC = "GET_LIST_goodsSaleC";
export const GET_LIST_adjust = "GET_LIST_adjust";
export const GET_LIST_award = "GET_LIST_award";
